fastlane_version "2.53.1"

default_platform :ios

platform :ios do
    before_all do
	ensure_git_status_clean

	carthage(platform: "iOS", cache_builds: true, use_submodules: true)
    end

    lane :production do
        increment_build_number

        match(type: "appstore", app_identifier: "Glasovac.WorkoutAppSnapKit")
        gym(scheme: "WorkoutAppSnapKit")

        pilot

	slack(
		message: "New app version available on Testflight",
		slack_url: "https://hooks.slack.com/services/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"
	)
    end

    lane :test do
        increment_build_number

        match(type: "adhoc", app_identifier: "Glasovac.WorkoutAppSnapKit")
        gym(scheme: "WorkoutAppSnapKit", configuration: "Debug")

        crashlytics(
            api_token: "002d1e80e7bf3a300de583f69a92347342fc38a9",
            build_secret: "e3df1c13235f9dab0dc7accc866329608184f2134ce261febd9bf33b9940b592",
            groups: "InitiativeTracker"
        )

    	version     = get_version_number(xcodeproj: "InitiativeTracker.xcodeproj")
    	build       = get_build_number(xcodeproj: "InitiativeTracker.xcodeproj")

    	slack(
      		message: "<!here|here>: New iOS *#{version}* (#{build}) :rocket:",
		slack_url: "https://hooks.slack.com/services/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"
	)
    end

  lane :devices do
    register_devices(devices_file: "./fastlane/devices.txt")

    match(type: "appstore", app_identifier: "com.Glasovac.WorkoutAppSnapKit", force_for_new_devices: true)
    match(type: "adhoc", app_identifier: "com.Glasovac.WorkoutAppSnapKit", force_for_new_devices: true)
    match(type: "development", app_identifier: "com.Glasovac.WorkoutAppSnapKit", force_for_new_devices: true)
  end

end

